name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [ARM64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up architecture-specific environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        if [ "${{ matrix.arch }}" = "ARM64" ]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        fi

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        if ("${{ matrix.arch }}" -eq "x64") {
          make
        } elseif ("${{ matrix.arch }}" -eq "ARM64") {
          make
        }
